#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 1000

#define DEBOUNCE 4

#define TAPPING_TOGGLE 2
#define TAPPING_TERM 90
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
