VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
OS_DETECTION_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODEMAP_ENABLE = yes
SPACE_CADET_ENABLE = yes

# size stuff
LTO_ENABLE = yes
GRAVE_ESC_ENABLE = no
