LTO_ENABLE = yes
VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
OS_DETECTION_ENABLE = yes

UNICODE_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MOUSEKEY_ENABLE = no