# special features
CAPS_WORD_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
# UNICODE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
VIA_ENABLE = yes

# saving space
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = no